Opex/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Opex.Models
{
    public class LoginViewModel
    {
        #region Properties  
        /// Gets or sets to username address.
        //  [Required(ErrorMessage = "نام کاربری الزامی است")]
        [Display(Name = "Username")]
        public string Username { get; set; }

        //Gets or sets to password address.  
        // [Required(ErrorMessage = "کلمه عبور را وارد کنید.")]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        #endregion
    }
}

Opex/Pages/Documents.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Opex.Models;

namespace Opex.Pages
{
    public class DocumentsModel : PageModel
    {
        private readonly DB_Context _context;
        public DocumentsModel(DB_Context context)
        {
            _context = context;
        }
        [TempData]
        public string Error { get; set; }
        public bool ShowMessage => !string.IsNullOrEmpty(Error);
        [TempData]
        public string TabPage { get; set; }
        public bool ShowTab => !string.IsNullOrEmpty(TabPage);
        public TblBinarys binarys { get; set; }
        public async Task<IActionResult> OnGet(int? id)
        {
            try
            {
                if (id == null)
                {
                    Error = "فایل یافت نشد.";
                    return RedirectToPage("/Binarys");
                }
                binarys = _context.TblBinarys.Where(b => b.BinaryId == id).FirstOrDefault();

                if (binarys == null)
                {
                    Error = "فایل یافت نشد.";
                    return RedirectToPage("/Error");
                }
                if (binarys.FileFormat == "pdf")
                    return File(binarys.Binary, "application/pdf");
                if (binarys.FileFormat == "png" || binarys.FileFormat == "jpg" || binarys.FileFormat == "jpeg")
                    return File(binarys.Binary, "image/png");
                return RedirectToPage("/Index");
            }
            catch (Exception ex)
            {

                Error = ex.Message.ToString();
                return RedirectToPage("/Error");
            }

        }
        public FileResult GetFileFromBytes(byte[] bytesIn)
        {
            if (binarys.FileFormat == "pdf")
                return File(bytesIn, "application/pdf");
            return File(bytesIn, "image/png");
        }
    }
}

Opex/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Opex.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
        [TempData]
        public string Error { get; set; }
        public bool ShowMessage => !string.IsNullOrEmpty(Error);
        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Opex/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Opex.Helpers;
using Opex.Models;

namespace Opex.Pages 
{
    public class IndexModel : PageModel
    {
        #region Private Properties. 
        [Required(ErrorMessage = "شماره تلفن همراه را وارد کنید")]
        [DataType(DataType.PhoneNumber)]
        [StringLength(13,ErrorMessage = "شماره همراه صحیح نیست", MinimumLength =11)]
        [RegularExpression(@"^\(?([0-9]{11})$", ErrorMessage = "شماره تلفن صحیح نیست")]
        public string PhoneNumber { get; set; }
        [TempData]
        public string Message { get; set; }
        public bool ShowMessage => !string.IsNullOrEmpty(Message);
        public IFormFile FormFile { get; set; }
        private readonly DB_Context dB_Context;
        #endregion
        public IndexModel(DB_Context databaseManagerContext)
        {
            try
            {
                this.dB_Context = databaseManagerContext;
            }
            catch (Exception ex)
            {
                // Info  
                Console.Write(ex);
            }
        }
        public IActionResult OnGet()
        {
            //var letternum = Services.NewLetterNum(dB_Context);
            HttpContext.Session.Clear();
            Response.Cookies.Delete("CodeMelli");
            if (User.Identity.IsAuthenticated)
                return RedirectToPage("/Senfi/Index");

            return Page();
        }
        #region Public Properties  
        /// Gets or sets login model property.  
        public Services service { get; set; }
        [BindProperty]
        public LoginViewModel LoginModel { get; set; }
        [BindProperty]
        public TblLetters tblLetter { get; set; }
        [BindProperty]
        public TblQuestionnaire Questionnaire { get; set; }
        [BindProperty]
        public TblRefrences TblRefrence { get; set; }
        [BindProperty]
        public TblBinarys tblbinary { get; set; }
        [BindProperty]
        public List<string> binaryIds { get; set; } 
        [BindProperty]
        public List<TblMembers> memberlist { get; set; }
        [BindProperty]
        public List<TblBinarys> BinaryList { get; set; }
        public byte[] Binary { get; set; }
        public bool Registered { get; set; }
        #endregion

        #region On Post Login method. 
        [HttpPost]
        public async Task<IActionResult> OnPostLogIn()
        {
            try
            {
                Response.Cookies.Delete("CodeMelli");
                // Verification.  
                if (ModelState.IsValid)
                {
                    if (LoginModel.Username == null || LoginModel.Password == null)
                    {
                        ViewData["Error"] = "نام کاربری و رمز عبور را وارد کنید.";
                        ViewData["OnTab"] = "rquest-type";
                        return Page();
                    }
                    // Initialization.  
                    var loginInfo = await this.LoginMethod(this.LoginModel.Username, this.LoginModel.Password);
                    // Verification.  
                    if (loginInfo != null && loginInfo.Count() > 0)
                    {
                        // Initialization.  
                        HttpContext.Session.SetString("CodeMelli", LoginModel.Username);
                        var logindetails = loginInfo.First();
                        Services.UserMemberId = logindetails.MemberId;
                        var id = this.SignInUser(logindetails.کدملی, false);
                        // Login In.  
                        await this.SignInUser(logindetails.نامخانوادگی, false); 
                        return RedirectToPage("/Senfi/Index");
                    }
                    else
                    {
                        ViewData["Error"] = "نام کاربری یا کلمه عبور اشتباه است.";
                        ViewData["OnTab"] = "rquest-type";
                        Registered = true;
                        return Page();
                    } 
                }
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
                // Info  
                return Page();
            }
            // Info.  
            TempData["message"] = "نام کاربری و کلمه عبور را وارد کنید.";
            ViewData["OnTab"] = "rquest-type";
            return Page();
        }
        #endregion
        #region Sign In method. 
        /// <returns>Returns - await task</returns>
        public async Task<List<TblMembers>> LoginMethod(string usernameVal, string passwordVal)
        {
            try
            {
                await Services.GetMember(dB_Context, usernameVal);
                if (Services.CurrentMember.کدملی == usernameVal && Services.CurrentMember.شمارهشناسنامه == passwordVal)
                    memberlist.Add(Services.CurrentMember);
                Services.RunInBackground(dB_Context);
                //binaryIds = Services.GetBinaryIds(Services.CurrentMember.BinaryIds);
            }
            catch (Exception ex)
            {
                ViewData["Error1"] = ex.Message.ToString(); 
                return null;
            }
            return memberlist;
        }
        private async Task SignInUser(string username, bool isPersistent)
        {
            // Initialization.  
            var claims = new List<Claim>();
            try
            {
                // Setting  
                claims.Add(new Claim(ClaimTypes.Name, username));
                claims.Add(new Claim(ClaimTypes.UserData, username));
                var claimIdenties = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var claimPrincipal = new ClaimsPrincipal(claimIdenties);
                var authenticationManager = Request.HttpContext;

                // Sign In.  
                await authenticationManager.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimPrincipal, new AuthenticationProperties() { IsPersistent = isPersistent });
            }
            catch (Exception ex)
            {
                // Info  
                throw ex;
            }
        }
        #endregion
        #region Rquest method.  
        public async Task<ActionResult> OnPostSendRequestAsync(IFormFile Binary , [StringLength(13, ErrorMessage = "تعداد ارقام صحیح نیست", MinimumLength = 11)] [RegularExpression(@"^(\+98|0)?9\d{9}$", ErrorMessage = "تلفن همراه نامعتبر است")]string PhoneNumber)
        {
            try
            { 
                if (Binary == null)
                {
                    TempData["nofile"] = "فایل انتخاب نشده است";
                    ViewData["OnTab"] = "rquest-type";
                    return Page();
                }
                if (!ModelState.IsValid)
                {
                    ViewData["OnTab"] = "rquest-type";
                    return Page();
                }
                if (PhoneNumber == null)
                {
                    TempData["noPhone"] = "تلفن همراه را وارد کنید ";
                    ViewData["OnTab"] = "rquest-type";
                    return Page();
                } 
                if(!await Services.RequestCheck(dB_Context,PhoneNumber))
                { 
                    TblBinarys tblBinarys = new TblBinarys();
                    var res = await Services.Upload(Binary);
                    if (res != null)
                    {
                        tblBinarys.Binary = res;
                        tblBinarys.Subject = "درخواست از سایت";
                        tblBinarys.Description = "ثبت از سایت";
                        tblBinarys.FileFormat = Path.GetExtension(Binary.FileName).Replace(".", "");
                        dB_Context.TblBinarys.Add(tblBinarys);
                        dB_Context.SaveChanges();
                    }
                    TblLetters NewLetter = new TblLetters
                    {
                        BinaryIds = tblBinarys.BinaryId.ToString(),
                        CreateDate = DateTime.Now,
                        SignDateTime = DateTime.Now,
                        Comment =  PhoneNumber,
                        LetterDate=Services.ToShamsi(DateTime.Now.Date),
                        Sender=15377,
                        Reciver=6519,
                        SubjectId=828,
                        Subjects= "درخواست عضويت در اتحاديه (سايت)",
                        Peyvast="دارد 1 برگ",
                        LetterNum ="",
                        DocumentType = "نامه",
                        Arjaiat = "عادی",
                        SendType = "اپلیکشن",
                        SubjectName = "",
                        SenderName = "متقاضي عضويت در اتحاديه",
                        ReciverName = "عباسعلي اسلامي -  رييس اتحاديه اتحاديه صادرکنندگان فراورده هاي نفت، گاز و پتروشيمي ايران",
                        LetterType = 0,
                        RelateLetterId = 0,
                        RelateLetterType = "وارده"
                    };
                     dB_Context.Add(NewLetter);
                     dB_Context.SaveChanges();
                    var id = NewLetter.LetterId;
                    TblRefrences refrence = new TblRefrences
                    {
                        LetterId = id,
                        ToUser = 57,
                        Status = 0,
                        FromUser = Services.UserMemberId,
                        ReferAbout = "درخواست از سایت",
                        Periority = "عادی"
                    };

Opex/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Opex.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Opex/Pages/Rols.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Opex.Pages
{
    public class RolsModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Opex/Pages/Summary.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Opex.Helpers;
using Opex.Models;

namespace Opex.Pages
{
    public class SummaryModel : PageModel
    {
        private readonly Opex.Models.DB_Context _context;
        public SummaryModel(DB_Context context)
        {
            _context = context;
        }
        [BindProperty]
        public TblMembers Members { get; set; }
        [BindProperty]
        public List<TblOfficeMember> OfficeMembers { get; set; }
        [BindProperty]
        public TblOfficeMembers FinancialBalance { get; set; }
        [BindProperty]
        public TblQuestionnaire Questionnaire { get; set; }
        [BindProperty]
        public List<TblBinarys> Binarys { get; set; }
        public bool MemberIsValid = true;
        public bool FinancialBalanceIsValid =true;
        public bool QuestionnaireIsValid = true;
        public bool OfficeMembersIsValid = true;
        public bool BinaryIsValid = true;
        public async Task<IActionResult> OnGet(int? id)

        {
            try
            {
                if (id == null)
                {
                    ViewData["message"] = "اطلاعات یافت نشد.";
                    MemberIsValid = false;
                    FinancialBalanceIsValid = false;
                    QuestionnaireIsValid = false;
                    OfficeMembersIsValid = false;
                    BinaryIsValid = false;
                    return Page();
                }
                Members = await _context.TblMembers.FirstOrDefaultAsync(m => m.MemberId == id);
                if (Members == null)
                {
                    ViewData["messageM"] = "اطلاعات  عضو یافت نشد.";
                    MemberIsValid = false;
                }
                OfficeMembers = await _context.TblOfficeMembers.Where(Om => Om.SystemCode == id).ToListAsync();
                if (OfficeMembers.Count<= 0|| OfficeMembers==null)
                {
                    ViewData["messageOM"] = "اطلاعات اعضاء هیئت مدیره یافت نشد.";
                    OfficeMembersIsValid = false;
                }
                FinancialBalance = await _context.TblFinancialBalances.FirstOrDefaultAsync(f => f.SystemCode == id);
                if (FinancialBalance == null)
                {
                    ViewData["messageFB"] = "اطلاعات مالی بازرگانی یافت نشد.";
                    FinancialBalanceIsValid = false;
                }
                Questionnaire = await _context.TblQuestionnaires.FirstOrDefaultAsync(q => q.SystemCode == id);
                if (Questionnaire == null)
                {
                    ViewData["messageQ"] = "اطلاعات پرسشنامه یافت نشد.";
                    QuestionnaireIsValid = false;
                }
                Binarys = await _context.TblBinarys.Where(b => b.CreateUser == Services.UserMemberId).ToListAsync();
                if (Binarys == null)
                {
                    ViewData["messageB"] = "مدارک بارگذاری نشده است.";
                    BinaryIsValid = false;
                }
                return Page();


            }
            catch (Exception ex)
            {
                ViewData["message"] = ex.Message;
                return Page();
            }

        }
    }
}

Opex/Pages/Documents.cshtml
@page
@model Opex.Pages.DocumentsModel
@{
    ViewData["Title"] = "Documents";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2>Documents</h2>

Opex/Pages/login.cshtml
@page
@model Opex.Pages.loginModel
@{
    ViewData["Title"] = "ورود به پنل کاربری";
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Opex</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href=""
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <link rel="apple-touch-icon" sizes="76x76" href="/img/apple-icon.png" />
    <link rel="icon" type="image/png" href="/img/favicon.png" />
    <title>درخواست صدور پروانه کسب</title>
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />
    <!-- CSS Files -->
    <link href="~/css/themify-icons-demo.css" rel="stylesheet" />
    <link href="~/css/demo.css" rel="stylesheet" />
    <link href="~/css/themify-icons.css" rel="stylesheet" />
    <link href="~/css/intlTelInput.css" rel="stylesheet" />
    <link rel="stylesheet" href="/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/css/bootstrap-rtl.min.css" />
    <link rel="stylesheet" href="/css/bootstrap-rtl.css" />
    <link rel="stylesheet" href="/css/boot.css" />
    <link rel="stylesheet" type='text/css' href="/css/fontawesome.css" />
    <link rel="stylesheet" type='text/css' href="/css/font-awesome.css" />
    <link rel="stylesheet" type='text/css' href="/css/fontawesome.min.css" />
    <link rel="stylesheet" type='text/css' href="/css/font-awesome.min.css" />
    <link rel="stylesheet" type='text/css' href="/css/style.css" />
    <!-- Fonts and Icons -->
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
    <link href="/css/themify-icons.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">

                    <div class="pull-left">
                        <img src="~/img/t-logo.png" style="width:50%;height:50%" />
                    </div>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Index"><span class="glyphicon glyphicon-home"></span> صفحه اصلی</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Rols"><span class="glyphicon glyphicon-list"></span> قوانین</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Register"><span class="glyphicon glyphicon-list-alt"></span> ثبت عضویت</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="/Correspondence/Index"><span class="glyphicon glyphicon-tasks"></span> مکاتبات</a>
                        </li> 
                    </ul>

                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <div class="col-sm-4 col-sm-offset-4 " style="margin-top:5%;">
            <div class="wizard-container">
                <div class="card wizard-card" style="min-height:330px">
                    <div class="wizard-header" style="font-family:SDF">
                        <h3 class="wizard-title">ورود به پنل کاربری</h3>
                        <br />
                        <p class="category"> درصورتی که قبلا ثبت درخواست انجام داده اید وارد پنل درخواست شوید.</p>
                        
                    </div>
                    <div class="col-sm-10 col-sm-offset-1 ">

                        @if (TempData["message"] != null)
                        {<div class="alert-danger">  @TempData["message"] </div>}
                        @if (ViewData["Error"] != null)
                        {<div class="alert-danger">  @ViewData["Error"] </div>}

                        <!-- Form -->
                        <form method="post" class="text-center" style="color: #757575;padding:15px">

                            <!-- Name -->
                            <div class="md-form mt-3">
                                @Html.TextBoxFor(m => m.LoginModels.Username, new { @class = "form-control mb-3", id = "materialSubscriptionFormPasswords", maxlength = "10", onkeypress = "javascript:return isNumber(event)", style = "direction:ltr", placeholder = "نام کاربري" })
                                @Html.ValidationMessageFor(m => m.LoginModels.Username, " ", new { @class = "text-danger" })
                                <label for="materialSubscriptionFormPasswords"> </label>
                            </div>
                            <!-- E-mai -->
                            <div class="md-form">
                                @Html.PasswordFor(m => m.LoginModels.Password, new { @class = "form-control mb-3", style = "direction:ltr", placeholder = "کلمه عبور" })
                                @Html.ValidationMessageFor(m => m.LoginModels.Password, " ", new { @class = "text-danger" })
                                <label for="materialSubscriptionFormPasswords"> </label>
                            </div>
                            <!-- Sign in button -->
                            <button type="submit" name="response" asp-page-handler="LogIn" class="btn btn-wd btn-primary btn-block">ورود</button>
                        </form>
                        <!-- Form -->

                    </div>
                   
                    </div>
                </div>
        </div>
    </div>

    <footer class="border-top footer text-muted" style="margin-top:7%">
        <div class="container text-dark text-center ">
            &copy; 1398 - اتحادیه صادرکنندگان فرآورده های نفت، گاز و پتروشیمی ایران - <a href="http://www.opex.ir">Opex</a> - <a asp-area="" asp-page="/Privacy">حریم خصوصی</a>
        </div>
    </footer>


    <!--   Core JS Files   -->
    <script src="/js/jquery-2.2.4.min.js" type="text/javascript"></script>
    <script src="/js/jquery-1.10.2.js" type="text/javascript"></script>
    <script src="/js/jquery-1.10.2.min.js" type="text/javascript"></script>
    <script src="/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/js/jquery.bootstrap.wizard.js" type="text/javascript"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <!--  Plugin for the Wizard -->
    <script src=" /js/demo.js" type="text/javascript"></script>
    <script src=" /js/paper-bootstrap-wizard.js" type="text/javascript"></script>

    <!--  More information about jquery.validate here: https://jqueryvalidation.org/	 -->
    <script src=" /js/jquery.validate.min.js" type="text/javascript"></script>

</body>
</html>